version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - apt-get update -y
      - apt-get install apt-transport-https gnupg -y
      - pip install codiga
      - apt-get update -y
      - apt-get install -y maven
    finally:
      - echo Preliminary tasks done
  pre_build:
    commands:
      #- codiga-check-quality --project "${CODIGA_PROJECT_NAME}" --min-quality-score 75  --sha "${CODEBUILD_RESOLVED_SOURCE_VERSION}" --max-timeout-sec 60
    finally:
      - echo pre-build done
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/API-1.0.jar

