name: CodeUp Deployment
on:
  push:
    branches:
      - halisia
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          name: rsa-key
          known_hosts: ${{ secrets.HOST_DNS }}
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '18'
          
      - name: Create private key file
        run: cd /home/runner/.ssh/ && echo "${{ secrets.EC2_SSH_KEY }}" > rsa-key.pem && chmod 400 rsa-key.pem 
          
      - name: Run Script
        run:  chmod 700 launch.sh && ./launch.sh 
      
      - name: Connect to EC2 with SSH
        run: sudo nohup ssh -o StrictHostKeyChecking=no -tt -i "/home/runner/.ssh/rsa-key.pem" ec2-user@${{ secrets.HOST_DNS }} & 
     
      - name: Copy jar file in EC2
        run: sudo scp -o StrictHostKeyChecking=no -tt -i "/home/runner/.ssh/rsa-key.pem" codeup/target/codeup-0.0.1-SNAPSHOT.jar ec2-user@${{ secrets.HOST_DNS }}:"/"

      - name: Run remote jar file
        run: java -Dspring.profiles.active=dev -jar codeup-0.0.1-SNAPSHOT.jar
#       - name: Run Script
#         run: ssh -o StrictHostKeyChecking=no -tt -i "/home/runner/.ssh/rsa-key.pem" ec2-user@${{ secrets.HOST_DNS }} 'bash -s' < launch.sh &
 
  deploy:
    needs: build
    name: Deploy 
    runs-on: ubuntu-latest

    steps:
     - name: Deploy to EC2
       uses: easingthemes/ssh-deploy@main
       env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
