name: CodeUp Deployment
on:
  push:
    branches:
      - halisia
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ./codeup
    steps:
      - uses: actions/checkout@v1
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          name: rsa-key
          known_hosts: ${{ secrets.HOST_DNS }}
      - name: Run ssh command
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.HOST_DNS }}
#       - name: Set up JDK
#         uses: actions/setup-java@v1
#         with:
#           java-version: '18'
#       - name: Pull the change from server
#         env:
#           USERNAME: ${{ secrets.GIT_USER }}
#           TOKEN: ${{ secrets.GIT_TOKEN }}
#         run: | 
#           git pull origin halisia
#           echo $USERNAME
#           echo $TOKEN
          
#       - name: Build with Maven
#         run: cd codeup && mvn clean install
#       - name: Upload JAR
#         uses: actions/upload-artifact@v2
#         with:
#           name: artifact
#           path: codeup/target/codeup-0.0.1-SNAPSHOT.jar
          
#       - name: Launch jar file
#         run: cd codeup/target && nohup java -jar codeup-0.0.1-SNAPSHOT.jar &
#         run: nohup java -jar codeup/targetcodeup-0.0.1-SNAPSHOT.jar &
      - name: Deploy EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

#   deploy:
#     needs: build
#     name: Deploy to EC2 
#     runs-on: ubuntu-latest

#     steps:
#       - name: Download JAR
#         uses: actions/download-artifact@v2
#         with:
#           name: artifact
#       - name: Checkout the files
#         uses: actions/checkout@v2
#       - name: Launch jar file
# #         run: cd codeup/target && java -jar codeup-0.0.1-SNAPSHOT.jar &
#       - name: Deploy to Server 1
#         uses: easingthemes/ssh-deploy@main
#         env:
#           SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
#           REMOTE_HOST: ${{ secrets.HOST_DNS }}
#           REMOTE_USER: ${{ secrets.USERNAME }}
#           TARGET: ${{ secrets.TARGET_DIR }}
