name: CodeUp Deployment
on:
  push:
    branches:
      - halisia
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ./codeup
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '18'
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GIT_API_HOST }}
          username: ${{ secrets.GIT_USER }}
          password: ${{ secrets.GIT_TOKEN }}
          port: ${{ secrets.SSH_PORT }}
          script: cd codeup && ${{ secrets.SCRIPT}}
      - name: Build with Maven
        run: cd codeup && mvn clean install
      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: codeup/target/codeup-0.0.1-SNAPSHOT.jar
      - name: Launch jar file
        run: cd codeup/target && java -jar codeup-0.0.1-SNAPSHOT.jar &
      - name: Check path
        run: pwd && ls codeup 
      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

#   deploy:
#     needs: build
#     name: Deploy to EC2 
#     runs-on: ubuntu-latest

#     steps:
#       - name: Download JAR
#         uses: actions/download-artifact@v2
#         with:
#           name: artifact
#       - name: Checkout the files
#         uses: actions/checkout@v2
#       - name: Launch jar file
# #         run: cd codeup/target && java -jar codeup-0.0.1-SNAPSHOT.jar &
#       - name: Deploy to Server 1
#         uses: easingthemes/ssh-deploy@main
#         env:
#           SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
#           REMOTE_HOST: ${{ secrets.HOST_DNS }}
#           REMOTE_USER: ${{ secrets.USERNAME }}
#           TARGET: ${{ secrets.TARGET_DIR }}
